name: Trigger Private Komodo Build

on:
  push:
    branches:
      - main

jobs:
  trigger-private-webhook:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Connect to Tailscale using the recommended OAuth method.
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: 'true'
          version: latest

      # Step 2: Trigger the Komodo webhook using the GitLab auth style.
      - name: Trigger Komodo Build Webhook
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-Gitlab-Token: ${{ secrets.KOMODO_WEBHOOK_SECRET }}" \
          -d '{"ref": "${{ github.ref }}"}' \
          "${{ secrets.KOMODO_WEBHOOK_URL }}"